### ISSUE TITLE
ScrollTop when choosing year or date when :inline="true"

### ISSUE THREAD

**Issue by annabala** [MahdadGhasemian/vue-datetime-js#10]
Hi, thanks for awesome plugin, it works good but I have a problem when I set my calendar to be inline within the template and I want to change date by clicking year or date then sometimes the scrollTop fires. How to prevent that? 
Here is my default options set:

```
Vue.use(VueDatetimeJs, {
  name: 'date-picker',
  props: {
    inputFormat: 'YYYY-MM-DD',
    format: 'jYYYY-jMM-jDD',
    editable: false,
    inputClass: '',
    color: '#fff',
    altName: "hidden_input_name",
    placeholder: "Please select a date",
    autoSubmit: false,
    inline: true,
  },
});
```
Thanks

**Comment by MahdadGhasemian** [comment]
hi
thanks and sorry for late.
please share your code to better debug.
this my example for inline mode :

https://codesandbox.io/s/suspicious-hugle-wmybq?file=/src/App.vue:221-225

by

**Comment by AbozahraOsama** [comment]
Hi @MahdadGhasemian,

How can I open and close the calendar in inline mode instead of being always open?

Thanks,

**Comment by MahdadGhasemian** [comment]
> Hi @MahdadGhasemian,
> 
> How can I open and close the calendar in inline mode instead of being always open?
> 
> Thanks,

HI @AbozahraOsama 

I'm sorry. it's not active yet.

**Comment by AbozahraOsama** [comment]
Ok thanks @MahdadGhasemian
