### ISSUE TITLE
component error while rendering

### ISSUE THREAD

**Issue by omduiji** [MahdadGhasemian/vue-datetime-js#26]
Hello, 

When I load the component for the first time it works properly, but when I select a date and close the calendar then opens it again it breaks up.
`<date-picker v-model="issueDate"  :locale="'ar-sa'" :calendar="'hijri'" element="dateInput" :wrapper-submit="true" appendTo=".container" :auto-submit="true" inputFormat="'jYYYY/jMM/jDD HH:mm'" ></date-picker>
![calendar_err](https://user-images.githubusercontent.com/24576901/155442230-ae2a3381-6959-4244-b4b5-d1df66e2b149.PNG)
`

**Comment by MahdadGhasemian** [comment]
added following to vue.config.js file :

```
var webpack = require("webpack");

module.exports = defineConfig({
  
  configureWebpack: {
    plugins: [
      new webpack.ContextReplacementPlugin(/moment[/\\]locale$/, /moment$/)
    ],
  }
});
```
