### ISSUE TITLE
integrating Hijri date picker with vue3

### ISSUE THREAD

**Issue by shehrozkapoor** [MahdadGhasemian/vue-datetime-js#30]
![Screen Shot 2022-04-22 at 2 44 57 AM](https://user-images.githubusercontent.com/59894229/164557396-7b9686e4-0f9d-44eb-8e70-dff7b74fb52b.png)
![Screen Shot 2022-04-22 at 2 37 10 AM](https://user-images.githubusercontent.com/59894229/164557826-aa9ebaaa-064e-4393-9f95-1cd2ec3ff4d5.png)
![Screen Shot 2022-04-22 at 2 31 11 AM](https://user-images.githubusercontent.com/59894229/164557638-92df378a-f790-4982-9c25-c05d37ba8d50.png)

<template>
  <div>
<date-picker v-model="date" :locale="'ar-sa'" :calendar="'hijri'"/>
  </div>
</template>

<script>
import VueDatetimeJs from 'vue-datetime-js'
export default {
  data(){
    return {
      date: ''
    }
  },
  components: {
    datePicker: VueDatetimeJs
  }
}
</script>

**Comment by MahdadGhasemian** [comment]
This component is not for vue3 , it's compiled only for vue2.
