### ISSUE TITLE
Input Format if language is ar-sa

### ISSUE THREAD

**Issue by emad-sure** [MahdadGhasemian/vue-datetime-js#8]
Having this calendar  of type hijri 
![image](https://user-images.githubusercontent.com/53175321/71781913-d3be5c00-2fdc-11ea-8e41-42911eae0a2f.png)
after selecting the value of my target date it gets formatted in arabic as well  
![image](https://user-images.githubusercontent.com/53175321/71781918-ec2e7680-2fdc-11ea-863a-c76af7cc7a1b.png)

How can i prevent that so that the value be well formatted to not get this issue 
![image](https://user-images.githubusercontent.com/53175321/71781933-0ff1bc80-2fdd-11ea-8322-a85206373ebf.png)

**Comment by MahdadGhasemian** [comment]
Hi
1- please install moment (npm install moment --save)
2- in main.js file insert this code in first of file:
import moment from 'moment';

```
moment.updateLocale('ar-sa', {
    postformat: function(string) {
        return string
            .replace(/\d/g, function(match) {
                return match;
            })
            .replace(/,/g, '،')
    }
})
```
