### ISSUE TITLE
localConfig fail

### ISSUE THREAD

**Issue by MockingMagician** [MahdadGhasemian/vue-datetime-js#9]
```js
Vue.use(VueDatetimeJs, {
    name: 'date-picker',
    props: {
        format: 'DD-MM-YYYY HH:mm',
        editable: false,
        inputClass: 'border-right form-control rounded-0',
        placeholder: "Sélectionnez la date et l'heure du rdv",
        color: '#3782C0',
        autoSubmit: false,
        locale: 'fr',
        localeConfig() {
            return {
                fr: {
                    dow: 0,
                    dir: 'ltr',
                    lang: {
                        label: 'label',
                        submit: 'valider',
                        cancel: 'annuler',
                        now: 'maintenant',
                        nextMonth: 'mois prochain',
                        prevMonth: 'mois précédent'
                    }
                }
            };
        },
        jumpMinute: 30,
    }
});
```
Hi, may be sure i'm doing something wrong, but may be you can give me an explanation. date-picker not take care of localeConfig in my implementation. So, all buttons (cancel, nextMonth...) are fallback in english. What i am doing wrong ?

**Comment by mehdad1420** [comment]
Hi, use `gregory ` in `localeConfig()` like this:
```
Vue.use(VueDatetimeJs, {
  name: "date-picker",
  props: {
    format: "DD-MM-YYYY HH:mm",
    editable: false,
    inputClass: "border-right form-control rounded-0",
    placeholder: "Sélectionnez la date et l'heure du rdv",
    color: "#3782C0",
    autoSubmit: false,
    locale: "fr",
    localeConfig() {
      return {
        gregory: {
          dow: 0,
          dir: "ltr",
          lang: {
            label: "label",
            submit: "valider",
            cancel: "annuler",
            now: "maintenant",
            nextMonth: "mois prochain",
            prevMonth: "mois précédent",
          },
        },
      };
    },
    jumpMinute: 30,
  },
});
```

**Comment by MockingMagician** [comment]
@mehdad1420 thanks I'll gonna try it and keep you updated. 
But according to the documentation it should be locale dependant... And I think my code was respectfully according on it. Documentation need an update ?

Most important, what if you want to display more than one language ?

**Comment by MockingMagician** [comment]
@mehdad1420 Great! I confirm it works with your solution. But it looks like it is not compliant about documentation. So something is wrong, or I am and miss something.

@MahdadGhasemian can you confirm ?

**Comment by mehdad1420** [comment]
Hi, document is wrong and it should be update.
thanks

**Comment by MockingMagician** [comment]
@mehdad1420 Ok happy to know I was not crazy about. So I let the issue open untill documentation is not updated.

I was thinking about, in my opinion buttons translations should not be located under the localeCnfig section, but directly in locales. If my understanding is good, localConfig relates more about the calendar type (gregorian, etc...), so maybe we should move button translation under locales and add locale property that fallback on callendar type.

If some interest, fallback me, we can discuss about, I will can do a PR with that implementation.

See U
